Repository neutrinojs/webpack-chain, pull requests merged in 2018-10, with the labels that each got.

#107 allow config entry to be an array or string
  src/Config.js
  test/Config.js
Labels: bug

#109 Switch from changelog to auto-changelog
  CHANGELOG.md
  package.json
  yarn.lock
Labels: docs

#84 Provide the same API for config.optimization.minimizer as config.plugins
  README.md
  src/Config.js
  src/Optimization.js
  test/Config.js
  test/Optimization.js
Labels: breaking change

#112 README: Add NPM/Travis badges
  README.md
Labels: docs

#116 Fix toString() output for alternative types of plugin
  src/Config.js
  src/Optimization.js
  src/Plugin.js
  src/Resolve.js
  test/Config.js
  test/Optimization.js
  test/Plugin.js
  test/Resolve.js
Labels: bug

#117 docs: fix typo
  README.md
Labels: docs
