Repository neutrinojs/webpack-chain, pull requests merged in 2019-12, with the labels that each got.

#136 add acho of chinese language
  README.md
Labels: docs

#213 Fix types for Config.resolve plugins and improve Plugin types
  package.json
  types/index.d.ts
  types/test/webpack-chain-tests.ts
  yarn.lock
Labels: bug

#215 README: Update Travis badge to point to travis-ci.com
  README.md
Labels: docs

#207 Add support for module.strictExportPresence and output.futureEmitAssets
  src/Module.js
  src/Output.js
  types/index.d.ts
  types/test/webpack-chain-tests.ts
Labels: enhancement

#218 fix: fix type definition for Rule#oneOf
  types/index.d.ts
  types/test/webpack-chain-tests.ts
Labels: bug

#221 Fix types for TypedChainedMap.getOrCompute missing
  types/index.d.ts
  types/test/webpack-chain-tests.ts
Labels: bug

#220 Add Rule.rules
  README.md
  src/Config.js
  src/Module.js
  src/Rule.js
  src/Use.js
  test/Config.js
  test/Rule.js
  test/Use.js
  types/index.d.ts
  types/test/webpack-chain-tests.ts
Labels: enhancement
