Repository neutrinojs/webpack-chain, pull requests merged in 2020-01, with the labels that each got.

#223 docs: Fix formatting typos in README
  README.md
Labels: docs

#224 docs: Correct the .merge() example for optimization.minimizer
  README.md
Labels: docs

#227 Add missing engines definition to package.json
  package.json
Labels: enhancement

#226 Improve error message when legacy minimizer syntax used
  src/Optimization.js
  test/Optimization.js
Labels: enhancement

#229 Validate that Plugin 'args' is an array
  src/Plugin.js
  test/Plugin.js
Labels: enhancement

#233 Update types and documentation for DevServer
  README.md
  types/index.d.ts
  types/test/webpack-chain-tests.ts
Labels: bug

#225 docs: Emphasise that merge() doesn't accept webpack config objects
  README.md
Labels: docs

#232 Add `devtoolNamespace` TypeScript declaration
  README.md
  types/index.d.ts
  types/test/webpack-chain-tests.ts
Labels: types
