Repository neutrinojs/webpack-chain, pull requests merged in 2020-07, with the labels that each got.

#265 Add rule.resolve
  README.md
  src/Rule.js
  test/Rule.js
  types/index.d.ts
  types/test/webpack-chain-tests.ts
Labels: enhancement

#267 Travis: Test against Node 14
  .travis.yml
Labels: development

#269 Remove unused dev-dependency @types/node
  package.json
  yarn.lock
Labels: development

#268 Clean up linting configuration
  .eslintignore
  .eslintrc.js
  .prettierignore
  .prettierrc.js
  .travis.yml
  package.json
  renovate.json
  types/index.d.ts
  types/test/webpack-chain-tests.ts
  yarn.lock
Labels: development

#270 Improve error message when .use() not called for a Plugin
  src/Plugin.js
  test/Plugin.js
Labels: enhancement

#271 Improve error message when .tap() used on an undefined plugin
  src/Plugin.js
  test/Plugin.js
Labels: enhancement

#273 Docs: Correct the documented version of Node supported
  README.md
Labels: docs
